<div id="av-layout-grid-6" class="av-layout-grid-container av-vn5v5p-9f3330b04d0ca8f122ac8df08c8952eb entry-content-wrapper main_color av-flex-cells  avia-builder-el-33  el_after_av_layout_row  el_before_av_layout_row  grid-row-not-first  container_wrap fullsize">
<div class="flex_cell av-k8s5vexa-758d30ef6c9f45b930df0a656bfcebe0 av-gridrow-cell av_one_full no_margin  avia-builder-el-34  avia-builder-el-no-sibling "><div class="flex_cell_inner">
<section class="av_textblock_section av-okdj4r-368c67896bd4401753b6a74350307a54" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock av_inherit_color" itemprop="text"><p style="text-align: left;"><span style="font-size: 34px; color: #0a0a0a; margin-top: 0px; line-height: 46px; text-align: center;"><b>Soal Sering Ditanya (FAQ)</b></span></p>
</div></section>
<div class="togglecontainer av-1sgx6ds-d4a741dc52f7559796047af7b3d73d46 avia-builder-el-36 el_after_av_textblock avia-builder-el-last toggle_close_all enable_toggles">
<section class="av_toggle_section av-1fuakuo-1ec748ccb93ab774831a0b9a808becad" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div role="tablist" class="single_toggle" data-tags="{All} "><p data-fake-id="#toggle-id-1" class="toggler" itemprop="headline" role="tab" tabindex="0" aria-controls="toggle-id-1" style="">Pergi ke luar negeri terlalu mahal <span class="toggle_icon"><span class="vert_icon"></span><span class="hor_icon"></span></span></p><div id="toggle-id-1" class="toggle_wrap" style=""><div class="toggle_content invers-color " itemprop="text"><p>Untuk aktivitas internasional tertentu, dukungan keuangan mungkin tersedia untuk memfasilitasi pengalaman luar negeri anda, namun demikian skema pendanaan akan tergantung pada jenis program dan perjanjian dengan lembaga mitra.</p>
</div></div></div></section>
<section class="av_toggle_section av-16pvvkg-f418fa45f7599121e304f2e03a788ae1" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div role="tablist" class="single_toggle" data-tags="{All} "><p data-fake-id="#toggle-id-2" class="toggler" itemprop="headline" role="tab" tabindex="0" aria-controls="toggle-id-2" style="">Saya tidak memiliki kemampuan bahasa Inggris yang memadai<span class="toggle_icon"><span class="vert_icon"></span><span class="hor_icon"></span></span></p><div id="toggle-id-2" class="toggle_wrap" style=""><div class="toggle_content invers-color " itemprop="text"><p>Mayoritas program yang ditawarkan di Universitas mitra di luar negeri dilakukan dalam bahasa Inggris, sehingga jika anda merasa bahwa kapasitas bahasa Inggris anda masih perlu ditingkatkan, anda dapat mengikuti kursus bahasa Inggris baik di pusat bahasa UII – CILACS atau di lembaga kursus bahasa lainnya di Yogyakarta. Kemampuan berbahasa Inggris akan menjadi salah satu manfaat berpartisipasi dalam kegiatan internasional.</p>
</div></div></div></section>
<section class="av_toggle_section av-mps3e8-ddbf34ff519c531843c48cfefe5123ea" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div role="tablist" class="single_toggle" data-tags="{All} "><p data-fake-id="#toggle-id-3" class="toggler" itemprop="headline" role="tab" tabindex="0" aria-controls="toggle-id-3" style="">Ikut mobilitas internasional akan memperlama masa studi saya<span class="toggle_icon"><span class="vert_icon"></span><span class="hor_icon"></span></span></p><div id="toggle-id-3" class="toggle_wrap" style=""><div class="toggle_content invers-color " itemprop="text"><p>Anda dapat memilih dari berbagai program yang sesuai dengan cita-cita dan kebutuhan anda. Program pendek dapat menjadi pilihan karena biasanya ditawarkan pada masa liburan semester. Selain itu, anda juga dapat berpartisipasi pada program transfer kredit&nbsp; dengan durasi satu semester yang memungkinkan anda untuk mendapatkan poin kredit akademik dari Universitas mitra UII. Partisipasi anda dalam setiap aktivitas mobilitas internasional akan memberikan anda peluang menimba pengalaman lintas budaya dan ketrampilan diri yang menjadikan nilai tambah pada kemampuan akademik anda.</p>
</div></div></div></section>
</div>
</div></div>
</div>
